<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation letter</title>
    <style>
        p {
            font-size: 23px;
            line-height: 36px;
            color: #0b0c0c;
        }
        a {
            font-style: italic;
            text-decoration: purple underline;
            color: #0b0c0c;
        }
    </style>
</head>
<body>
    <p>Hi, honey! Thank you for registering :)<br>
    Please <a href="${link}">click on the link</a> to activate your account<br>
    See you soon!</p>
</body>
</html>